"""
analysis/report_builder.py
===========================
Builds downloadable reports: JSON and PDF.
"""

import json
import io
from datetime import datetime
from typing import Optional


def build_json_report(
    filename: str,
    analysis: dict,
    risks: list,
    key_terms: dict,
    score: int,
    level: str,
    pages: int,
) -> dict:
    """Build a structured JSON report dict."""
    return {
        "metadata": {
            "tool": "ContractAI — Enterprise Contract Analyzer",
            "version": "1.0.0",
            "generated_at": datetime.now().isoformat(),
            "filename": filename,
            "pages": pages,
        },
        "summary": analysis.get("summary", ""),
        "contract_type": analysis.get("contract_type", "Unknown"),
        "parties": analysis.get("parties", []),
        "risk_assessment": {
            "score": score,
            "level": level,
            "total_risks": len(risks),
            "critical": len([r for r in risks if r["severity"] == "Critical"]),
            "high": len([r for r in risks if r["severity"] == "High"]),
            "medium": len([r for r in risks if r["severity"] == "Medium"]),
            "low": len([r for r in risks if r["severity"] == "Low"]),
        },
        "key_terms": key_terms,
        "critical_dates": analysis.get("critical_dates", []),
        "obligations": analysis.get("obligations", []),
        "red_flags": [
            {
                "risk_id": r.get("risk_id"),
                "category": r.get("category"),
                "severity": r.get("severity"),
                "title": r.get("title"),
                "explanation": r.get("explanation"),
                "clause_snippet": r.get("clause_snippet", ""),
                "recommendation": r.get("recommendation"),
            }
            for r in risks
        ],
        "disclaimer": (
            "This report is generated by ContractAI for informational purposes only. "
            "It does not constitute legal advice. Always consult a qualified legal professional."
        ),
    }


def build_pdf_report(
    filename: str,
    analysis: dict,
    risks: list,
    key_terms: dict,
    score: int,
    level: str,
    summary: str,
) -> bytes:
    """
    Build a PDF report using reportlab.
    Falls back to fpdf2 if reportlab is unavailable.
    """
    try:
        return _build_with_reportlab(filename, analysis, risks, key_terms, score, level, summary)
    except ImportError:
        pass

    try:
        return _build_with_fpdf(filename, analysis, risks, key_terms, score, level, summary)
    except ImportError:
        raise RuntimeError("Neither reportlab nor fpdf2 is installed. Cannot generate PDF report.")


# ─── ReportLab implementation ─────────────────────────────────────────────────
def _build_with_reportlab(filename, analysis, risks, key_terms, score, level, summary) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        HRFlowable, KeepTogether,
    )
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
        title="Contract Analysis Report",
        author="ContractAI",
    )

    styles = getSampleStyleSheet()

    # ── Custom styles ─────────────────────────────────────────────────────────
    INDIGO = colors.HexColor("#4f46e5")
    DARK   = colors.HexColor("#0f172a")
    MUTED  = colors.HexColor("#64748b")
    SUCCESS = colors.HexColor("#22c55e")
    WARNING = colors.HexColor("#f59e0b")
    DANGER  = colors.HexColor("#ef4444")
    LIGHT_BG = colors.HexColor("#f8fafc")

    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=22, textColor=DARK,
                         leading=28, spaceAfter=6, fontName="Helvetica-Bold")
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=14, textColor=INDIGO,
                         leading=18, spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold")
    h3 = ParagraphStyle("H3", parent=styles["Heading3"], fontSize=11, textColor=DARK,
                         leading=15, spaceBefore=8, spaceAfter=4, fontName="Helvetica-Bold")
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, textColor=DARK,
                           leading=14, spaceAfter=4)
    muted = ParagraphStyle("Muted", parent=styles["Normal"], fontSize=8, textColor=MUTED,
                            leading=12, spaceAfter=3)
    caption = ParagraphStyle("Caption", parent=styles["Normal"], fontSize=8, textColor=MUTED,
                              alignment=TA_RIGHT)

    severity_colors = {
        "Critical": colors.HexColor("#fee2e2"),
        "High":     colors.HexColor("#ffe4e6"),
        "Medium":   colors.HexColor("#fef3c7"),
        "Low":      colors.HexColor("#dcfce7"),
    }
    severity_text_colors = {
        "Critical": colors.HexColor("#991b1b"),
        "High":     colors.HexColor("#be123c"),
        "Medium":   colors.HexColor("#92400e"),
        "Low":      colors.HexColor("#166534"),
    }
    score_color = SUCCESS if level == "Low" else (WARNING if level == "Medium" else DANGER)

    story = []

    # ── Header ────────────────────────────────────────────────────────────────
    header_data = [[
        Paragraph("<b><font color='#4f46e5'>ContractAI</font></b> — Enterprise Contract Analyzer", h1),
        Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}", caption),
    ]]
    header_table = Table(header_data, colWidths=["75%", "25%"])
    header_table.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "BOTTOM"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(header_table)
    story.append(HRFlowable(width="100%", thickness=2, color=INDIGO, spaceAfter=10))

    # ── Report meta ───────────────────────────────────────────────────────────
    story.append(Paragraph(f"<b>File:</b> {filename}", muted))
    story.append(Paragraph(f"<b>Contract Type:</b> {analysis.get('contract_type', 'Unknown')}", muted))
    parties = analysis.get("parties", [])
    if parties:
        story.append(Paragraph(f"<b>Parties:</b> {', '.join(parties[:3])}", muted))
    story.append(Spacer(1, 12))

    # ── Risk score banner ─────────────────────────────────────────────────────
    score_label = f"Risk Score: {score}/100  —  {level.upper()} RISK"
    score_banner_data = [[Paragraph(f"<b><font color='white'>{score_label}</font></b>",
                                     ParagraphStyle("ScoreBanner", fontSize=13, fontName="Helvetica-Bold",
                                                    alignment=TA_CENTER))]]
    score_banner = Table(score_banner_data, colWidths=["100%"])
    score_banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), score_color),
        ("ROUNDEDCORNERS", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(score_banner)
    story.append(Spacer(1, 10))

    # ── Risk metrics row ──────────────────────────────────────────────────────
    critical = len([r for r in risks if r["severity"] == "Critical"])
    high     = len([r for r in risks if r["severity"] == "High"])
    medium   = len([r for r in risks if r["severity"] == "Medium"])
    low      = len([r for r in risks if r["severity"] == "Low"])

    metrics_data = [
        [
            Paragraph(f"<b>{critical + high}</b><br/><font size=8 color='#64748b'>Critical/High</font>",
                      ParagraphStyle("M", alignment=TA_CENTER, fontSize=18)),
            Paragraph(f"<b>{medium}</b><br/><font size=8 color='#64748b'>Medium</font>",
                      ParagraphStyle("M", alignment=TA_CENTER, fontSize=18)),
            Paragraph(f"<b>{low}</b><br/><font size=8 color='#64748b'>Low</font>",
                      ParagraphStyle("M", alignment=TA_CENTER, fontSize=18)),
            Paragraph(f"<b>{len(risks)}</b><br/><font size=8 color='#64748b'>Total Risks</font>",
                      ParagraphStyle("M", alignment=TA_CENTER, fontSize=18)),
        ]
    ]
    metrics_table = Table(metrics_data, colWidths=["25%", "25%", "25%", "25%"])
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), colors.HexColor("#fee2e2")),
        ("BACKGROUND", (1, 0), (1, 0), colors.HexColor("#fef3c7")),
        ("BACKGROUND", (2, 0), (2, 0), colors.HexColor("#dcfce7")),
        ("BACKGROUND", (3, 0), (3, 0), colors.HexColor("#f1f5f9")),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 14))

    # ── Executive Summary ─────────────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", h2))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=8))
    story.append(Paragraph(summary or "No summary available.", body))
    story.append(Spacer(1, 12))

    # ── Key Terms ─────────────────────────────────────────────────────────────
    story.append(Paragraph("Key Contract Terms", h2))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=8))

    terms_data = [["Term", "Extracted Value"]]
    for term, value in key_terms.items():
        terms_data.append([
            Paragraph(f"<b>{term}</b>", ParagraphStyle("TC", fontSize=8, fontName="Helvetica-Bold")),
            Paragraph(str(value) if value else "Not found",
                      ParagraphStyle("TV", fontSize=8, textColor=MUTED if not value or value == "Not found" else DARK)),
        ])

    terms_table = Table(terms_data, colWidths=["40%", "60%"])
    terms_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), INDIGO),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(terms_table)
    story.append(Spacer(1, 14))

    # ── Critical Dates ────────────────────────────────────────────────────────
    critical_dates = analysis.get("critical_dates", [])
    if critical_dates:
        story.append(Paragraph("Critical Dates", h2))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=8))
        dates_data = [["Date Type", "Date", "Context"]]
        for d in critical_dates:
            dates_data.append([d.get("Type", ""), d.get("Date", ""), d.get("Context", "")])
        dates_table = Table(dates_data, colWidths=["35%", "30%", "35%"])
        dates_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), INDIGO),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(dates_table)
        story.append(Spacer(1, 14))

    # ── Risk Analysis ─────────────────────────────────────────────────────────
    story.append(Paragraph("Risk Analysis", h2))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=8))

    severity_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
    sorted_risks = sorted(risks, key=lambda r: severity_order.get(r.get("severity", "Low"), 4))

    risk_table_data = [["ID", "Severity", "Category", "Title"]]
    for r in sorted_risks:
        risk_table_data.append([
            r.get("risk_id", ""),
            r.get("severity", ""),
            r.get("category", ""),
            Paragraph(r.get("title", ""), ParagraphStyle("RT", fontSize=8)),
        ])

    risk_header_table = Table(risk_table_data, colWidths=["8%", "14%", "18%", "60%"])
    risk_tbl_style = [
        ("BACKGROUND", (0, 0), (-1, 0), INDIGO),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]
    for i, r in enumerate(sorted_risks, 1):
        sev = r.get("severity", "Low")
        bg = severity_colors.get(sev, colors.white)
        tc = severity_text_colors.get(sev, DARK)
        risk_tbl_style.append(("BACKGROUND", (1, i), (1, i), bg))
        risk_tbl_style.append(("TEXTCOLOR", (1, i), (1, i), tc))
        risk_tbl_style.append(("FONTNAME", (1, i), (1, i), "Helvetica-Bold"))

    risk_header_table.setStyle(TableStyle(risk_tbl_style))
    story.append(risk_header_table)
    story.append(Spacer(1, 10))

    # Detailed risk entries
    for r in sorted_risks[:8]:  # Cap at 8 for PDF length
        sev = r.get("severity", "Low")
        bg = severity_colors.get(sev, LIGHT_BG)

        risk_detail = [
            [Paragraph(f"<b>[{sev}] {r.get('title', '')}</b>",
                       ParagraphStyle("RDT", fontSize=9, fontName="Helvetica-Bold",
                                       textColor=severity_text_colors.get(sev, DARK)))],
            [Paragraph(r.get("explanation", ""), ParagraphStyle("RDE", fontSize=8, textColor=DARK, leading=12))],
            [Paragraph(f"<b>Recommendation:</b> {r.get('recommendation', '')}",
                       ParagraphStyle("RDR", fontSize=8, textColor=MUTED, leading=12, fontName="Helvetica-Oblique"))],
        ]
        if r.get("clause_snippet") and len(r["clause_snippet"]) > 10:
            snippet = r["clause_snippet"][:200] + ("…" if len(r["clause_snippet"]) > 200 else "")
            risk_detail.append([
                Paragraph(f"<i>&ldquo;{snippet}&rdquo;</i>",
                           ParagraphStyle("RDS", fontSize=7.5, textColor=MUTED, leading=11))
            ])

        detail_tbl = Table(risk_detail, colWidths=["100%"])
        detail_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bg),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ]))
        story.append(KeepTogether(detail_tbl))
        story.append(Spacer(1, 6))

    # ── Disclaimer ────────────────────────────────────────────────────────────
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0"), spaceAfter=8))
    story.append(Paragraph(
        "⚖️ Disclaimer: This report is generated by ContractAI for informational purposes only. "
        "It does not constitute legal advice. Always consult a qualified legal professional before acting on this analysis.",
        ParagraphStyle("Disc", fontSize=7.5, textColor=MUTED, leading=11, fontName="Helvetica-Oblique")
    ))

    doc.build(story)
    return buf.getvalue()


# ─── fpdf2 fallback ───────────────────────────────────────────────────────────
def _build_with_fpdf(filename, analysis, risks, key_terms, score, level, summary) -> bytes:
    from fpdf import FPDF

    class PDF(FPDF):
        def header(self):
            self.set_font("Helvetica", "B", 14)
            self.set_text_color(79, 70, 229)
            self.cell(0, 10, "ContractAI — Contract Analysis Report", align="L", new_x="LMARGIN", new_y="NEXT")
            self.set_font("Helvetica", size=8)
            self.set_text_color(100, 116, 139)
            self.cell(0, 5, f"Generated: {datetime.now().strftime('%B %d, %Y %H:%M')}",
                      align="R", new_x="LMARGIN", new_y="NEXT")
            self.ln(3)

        def footer(self):
            self.set_y(-15)
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(100, 116, 139)
            self.cell(0, 10, f"Page {self.page_no()} | ContractAI — Not Legal Advice", align="C")

    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    def section_title(title):
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(79, 70, 229)
        pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(226, 232, 240)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

    def body_text(text, color=(15, 23, 42)):
        pdf.set_font("Helvetica", size=9)
        pdf.set_text_color(*color)
        pdf.multi_cell(0, 5, text)
        pdf.ln(2)

    score_colors = {"Low": (34, 197, 94), "Medium": (245, 158, 11), "High": (239, 68, 68), "Critical": (153, 27, 27)}
    sc = score_colors.get(level, (79, 70, 229))
    pdf.set_fill_color(*sc)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 12, f"Risk Score: {score}/100  —  {level.upper()} RISK", fill=True,
             align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Helvetica", size=9)
    pdf.cell(0, 5, f"File: {filename}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Contract Type: {analysis.get('contract_type', 'Unknown')}", new_x="LMARGIN", new_y="NEXT")

    section_title("Executive Summary")
    body_text(summary or "No summary available.")

    section_title("Key Terms")
    for term, value in key_terms.items():
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(60, 5, term + ":", new_x="RIGHT", new_y="LAST")
        pdf.set_font("Helvetica", size=8)
        pdf.set_text_color(100, 116, 139)
        pdf.multi_cell(0, 5, str(value) if value else "Not found", new_x="LMARGIN", new_y="NEXT")

    section_title("Risk Analysis")
    severity_order = {"Critical": 0, "High": 1, "Medium": 2, "Low": 3}
    sorted_risks = sorted(risks, key=lambda r: severity_order.get(r.get("severity", "Low"), 4))
    for r in sorted_risks:
        sev = r.get("severity", "Low")
        sev_colors = {"Critical": (153, 27, 27), "High": (190, 18, 60), "Medium": (146, 64, 14), "Low": (22, 101, 52)}
        tc = sev_colors.get(sev, (15, 23, 42))
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*tc)
        pdf.cell(0, 6, f"[{sev}] {r.get('title', '')}", new_x="LMARGIN", new_y="NEXT")
        body_text(r.get("explanation", ""), color=(15, 23, 42))
        body_text(f"Recommendation: {r.get('recommendation', '')}", color=(100, 116, 139))
        pdf.ln(2)

    section_title("Disclaimer")
    body_text(
        "This report is generated by ContractAI for informational purposes only and does not "
        "constitute legal advice. Always consult a qualified legal professional.",
        color=(100, 116, 139)
    )

    return pdf.output()
